package com.karyakita.karyakita_android_new.base_class_interface;

public class GlobalVariable {
    public static String TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImNyZWF0ZWRBdCI6IjIwMTgtMTAtMDFUMTA6MzI6MTAuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMTgtMTAtMDFUMTA6MzI6MTAuMDAwWiIsImlkIjo0LCJlbWFpbCI6ImFkbWluM0BrYXJ5YWtpdGEuY29tIiwidXNlcm5hbWUiOiJhZG1pbjMiLCJuYW1hIjoiQXNtaSIsIm5vdGVscCI6IjEyMzEyMzEyMzEiLCJyb2xlX2lkIjoxfSwiaWF0IjoxNTM4NDc1MDA2LCJleHAiOjE1Mzk0NzUwMDZ9.ntUxSxAndiraTbNmmcbENXnx3lBmEYMYl9xCE3yBmt0";
}
